"""Freeze + wiring test for the anchor calibration snapshot (Phase A2).

The snapshot src/pmb/lang/anchor_calibration.json is generated by
scripts/calibrate_anchors.py on the real multilingual embedder. These tests:

  1. FREEZE   — the committed snapshot's `key` still matches the key produced by
                the CURRENT anchor definitions + the snapshot's model. Editing an
                anchor's exemplars (or swapping the embedder) changes the key, so
                this fails loudly until someone reruns the calibration. That is
                the guard against silently scoring new anchors with stale taus.
  2. QUALITY  — every set met the FPR budget and no set's recall collapsed.
  3. WIRING   — AnchorIndex loads the snapshot when the key matches and IGNORES
                it (falls back to dataclass placeholders) when it doesn't. Run
                with a fake embedder, so it's hermetic and model-free.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from pmb.lang.anchors import (
    ALL_ANCHORS,
    CALIBRATION_FILE,
    AnchorIndex,
)

_SNAP_PATH = next(
    p for p in Path(__file__).resolve().parents if (p / "pyproject.toml").is_file()
) / "src" / "pmb" / "lang" / CALIBRATION_FILE


def _snapshot() -> dict:
    return json.loads(_SNAP_PATH.read_text(encoding="utf-8"))


def _fake_embed(dim: int = 16):
    """Deterministic, model-free embedder. The values are irrelevant to the
    cache/calibration KEY (which hashes model id + anchor text only), so this
    lets us exercise the loader without loading sentence-transformers."""
    def embed_batch(texts):
        out = np.zeros((len(texts), dim), dtype=np.float32)
        for i, t in enumerate(texts):
            h = abs(hash(t))
            for j in range(dim):
                out[i, j] = ((h >> j) & 0xFF) / 255.0
        return out
    return embed_batch


def test_snapshot_exists_and_covers_every_anchor():
    snap = _snapshot()
    assert snap.get("schema") == 1
    assert snap.get("key")
    assert snap.get("model_id")
    names = {s.name for s in ALL_ANCHORS}
    assert set(snap["sets"].keys()) == names, \
        "calibration must cover exactly the current anchor sets"


def test_freeze_key_matches_current_anchor_defs(tmp_path):
    """If this fails, the anchor exemplars changed since calibration — rerun
    `python scripts/calibrate_anchors.py` and commit the new snapshot."""
    snap = _snapshot()
    idx = AnchorIndex(_fake_embed(), snap["model_id"], ALL_ANCHORS, tmp_path)
    assert idx._key == snap["key"], (
        "anchor definitions drifted from the calibration snapshot — "
        "rerun scripts/calibrate_anchors.py"
    )


def test_quality_gate_fpr_budget_and_recall():
    snap = _snapshot()
    max_fpr = float(snap.get("max_fpr", 0.01))
    for name, row in snap["sets"].items():
        # Realized FPR must respect the budget (a little slack for the single
        # tolerated false positive on a finite negative pool).
        assert row["fpr"] <= max_fpr * 1.6, f"{name}: fpr {row['fpr']} over budget"
        # No set may collapse to near-zero recall — that would mean the embedder
        # can't separate the class at all and the anchor is useless.
        assert row["recall"] >= 0.5, f"{name}: recall {row['recall']} collapsed"
    assert snap["macro"]["recall"] >= 0.80
    assert snap["macro"]["fpr"] <= max_fpr


def test_runtime_loads_calibration_when_key_matches(tmp_path):
    snap = _snapshot()
    idx = AnchorIndex(_fake_embed(), snap["model_id"], ALL_ANCHORS, tmp_path)
    assert idx.calibrated is True
    # Calibrated taus replaced the 0.10 placeholders, per the snapshot.
    for name, row in snap["sets"].items():
        assert idx._tau[name] == pytest.approx(row["tau"], abs=1e-6)
        assert idx._floor[name] == pytest.approx(row["floor"], abs=1e-6)
    # At least one set actually moved off the placeholder (sanity that the
    # snapshot isn't a no-op).
    assert any(idx._tau[s.name] != s.tau for s in ALL_ANCHORS)


def test_runtime_ignores_calibration_on_model_mismatch(tmp_path):
    # A different model id → different key → snapshot must be ignored and the
    # dataclass placeholders kept (never score new embedder with old taus).
    idx = AnchorIndex(_fake_embed(), "some-other-embedder-v9", ALL_ANCHORS,
                      tmp_path)
    assert idx.calibrated is False
    for s in ALL_ANCHORS:
        assert idx._tau[s.name] == s.tau
        assert idx._floor[s.name] == s.floor
